#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define T_FREEZE_DANGER_DEFAULT_C 0
#define K 1.5
#define RELAY_PIN 33
#define TEMP_SENSOR_PIN 34

#define LED_PIN 2
#define LED_ON_PERIOD_MS 250 / portTICK_PERIOD_MS
#define NORMAL_HEARTBEAT_PERIOD_MS 5000 / portTICK_PERIOD_MS
#define FREEZE_DANGER_HEARTBEAT_PERIOD_MS 1000 / portTICK_PERIOD_MS
#define RELAY_ACTIVATED_HEARTBEAT_PERIOD_MS 500 / portTICK_PERIOD_MS

#define MDNS_HOSTNAME antifreeze
#define MDNS_SERVICENAME antifreeze

#endif
